docs_dir: _build/pydocmd
pages:
- {Home: index.md}
- sequence:
  - {Sequence: docs/Sequence.md}
  - {DNASequence: docs/DNASequence.md}
  - {RNASequence: docs/RNASequence.md}
- {region: docs/Region.md}
site_dir: docs
site_name: Genomics Documentation
theme: readthedocs
