docs_dir: _build/pydocmd

pages:
- {Home: index.md}
- annotations:
  - {Annotation: docs/Annotation.md}
  - {AnnotationTable: docs/AnnotationTable.md}
- gene:
  - {Gene: docs/Gene.md}
  - {GeneTable: docs/GeneTable.md}
- region:
  - {Region: docs/Region.md}
  - {DisjointRegion: docs/DisjointRegion.md}
  - {RegionTable: docs/RegionTable.md}
- sequence:
  - {Sequence: docs/Sequence.md}
  - {DNA: docs/DNA.md}
  - {RNA: docs/RNA.md}
  - {AminoAcids: docs/AminoAcids.md}
  - {SequenceSet: docs/SequenceSet.md}
- variant:
  - {Variant: docs/Variant.md}
  - {VariantTable: docs/VariantTable.md}

site_dir: docs
site_name: Genomics Documentation
theme: readthedocs
